# Generated by Django 4.2.4 on 2024-05-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_order_id_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Pay On Delivery'), ('paypal', 'Paypal'), ('rzp', 'Razor Pay')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'Processing'), ('payment_pending', 'Payment Pending'), ('confirm', 'Confrimed'), ('ship', 'Shipped'), ('diliver', 'Delivered')], default='process', max_length=15),
        ),
    ]
