# Generated by Django 4.2.4 on 2024-05-26 19:30

from django.db import migrations, models
import products.models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=products.models.banner_image)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
